from __future__ import annotations
from typing import Iterable, Iterator, Literal, Optional, Protocol, runtime_checkable
from ..domain.models import Camp, Review, Concept, Theme, CampConcept, Mark


@runtime_checkable
class CampReader(Protocol):
    def get(self, camp_id: str) -> Optional[Camp]: ...
    def list_filtered(
        self, *,
        sido: Optional[str] = None, sigungu: Optional[str] = None,
        concept: list[str] | None = None,
        concepts_any: list[str] | None = None,
        min_score: float | None = None, max_score: float | None = None,
        bbox: tuple[float, float, float, float] | None = None,
        ids: list[str] | None = None,
        limit: int = 2000,
    ) -> list[Camp]: ...
    def iter_all(self) -> Iterator[Camp]: ...
    def count(self) -> int: ...


@runtime_checkable
class CampWriter(Protocol):
    def upsert_many(self, camps: Iterable[Camp]) -> int: ...
    def set_geo(self, camp_id: str, lat: float, lon: float) -> None: ...
    def delete(self, camp_id: str) -> bool: ...


@runtime_checkable
class ReviewReader(Protocol):
    def top_for(self, camp_id: str, n: int = 3,
                sort: Literal["score", "recent"] = "score") -> list[Review]: ...
    def total_for(self, camp_id: str) -> int: ...
    def iter_for(self, camp_id: str) -> Iterator[Review]: ...


@runtime_checkable
class ReviewWriter(Protocol):
    def upsert_many(self, reviews: Iterable[Review]) -> int: ...


@runtime_checkable
class ConceptRepository(Protocol):
    def upsert_concept(self, c: Concept) -> None: ...
    def assign(self, camp_id: str, concept_id: str, score: float, evidence: str | None = None) -> None: ...
    def for_camp(self, camp_id: str) -> list[CampConcept]: ...
    def all(self) -> list[Concept]: ...
    # Used by BuildVocabulary to resolve UNIQUE(name) collisions when a
    # curated seed wants a name that an auto-derived row already holds.
    def find_by_name(self, name: str) -> Optional[Concept]: ...
    def delete_by_id(self, concept_id: str) -> None: ...


@runtime_checkable
class ThemeRepository(Protocol):
    def replace_all(self, themes: list[Theme]) -> None: ...
    def assign(self, camp_id: str, theme_id: str) -> None: ...
    def for_camp(self, camp_id: str) -> Optional[Theme]: ...
    def all(self) -> list[Theme]: ...


@runtime_checkable
class CamfitFilterRepository(Protocol):
    """Stores camfit's native taxonomy (themes / inventory filters / collections)."""
    def upsert(self, filter_id: str, name: str, kind: str, raw: dict | None) -> None: ...
    def all(self) -> list[tuple[str, str, str]]: ...  # (id, name, kind)


@runtime_checkable
class FilterConceptMappingRepository(Protocol):
    def upsert_mapping(self, filter_id: str, concept_id: str, polarity: int) -> None: ...
    def for_filter(self, filter_id: str) -> list[tuple[str, int]]: ...  # (concept_id, polarity)


@runtime_checkable
class FilterSignalWriter(Protocol):
    def upsert(self, camp_id: str, concept_id: str, score: float, evidence: str | None) -> None: ...
    def reset_for(self, camp_id: str) -> None: ...


@runtime_checkable
class DescSignalWriter(Protocol):
    def upsert(self, camp_id: str, concept_id: str, score: float) -> None: ...
    def reset_for(self, camp_id: str) -> None: ...


@runtime_checkable
class ReviewSignalWriter(Protocol):
    def upsert(self, camp_id: str, concept_id: str, score: float,
               pos_count: int, neg_count: int, evidence: str | None) -> None: ...
    def reset_for(self, camp_id: str) -> None: ...


@runtime_checkable
class MarkRepository(Protocol):
    def replace_for_camp(self, camp_id: str, marks: list["Mark"]) -> int: ...
    def for_camp(self, camp_id: str) -> list["Mark"]: ...
    def for_axis(self, axis: str, *, min_level: str | None = None,
                 limit: int = 100) -> list["Mark"]: ...
    def all_axes(self) -> list[tuple[str, int]]:
        """[(axis_name, count), ...] ordered by count desc."""
        ...
