from __future__ import annotations
from typing import Iterable, Optional, Protocol, runtime_checkable
import numpy as np


@runtime_checkable
class VectorIndex(Protocol):
    @property
    def dim(self) -> int: ...
    def upsert_many(self, items: Iterable[tuple[str, np.ndarray, str]]) -> int: ...
    def knn(self, query: np.ndarray, k: int = 10,
            filter_ids: set[str] | None = None) -> list[tuple[str, float]]: ...
    def get(self, item_id: str) -> Optional[np.ndarray]: ...
    def size(self) -> int: ...
    def reset(self) -> None: ...
