"""Curated concept seed list. Each entry: (id, name, category, is_axis).

Sources beyond this list (hashtag, facility) are auto-generated by
BuildVocabulary using `source='hashtag'` or `source='facility'`.

This list reflects the P2 spec addendum (5 important filter dimensions):
  D1 surface, D2 management→marks(separate), D3 view, D4 space+parking, D5 kids_facility.

Categories used (free-form, but conventional):
  audience, environment, facility, type, vibe, season, activity,
  surface, view, space, parking, kids_facility, mark
"""

# (id, korean_name, category, is_axis)
SEEDS: list[tuple[str, str, str, bool]] = [
    # ── Audience axes ─────────────────────────────────────────
    ("kids",         "키즈캠핑",   "audience",     True),
    ("pets",         "반려동반",   "audience",     True),
    # ── Environment / view ───────────────────────────────────
    ("valley",       "계곡",       "environment",  True),
    ("oceanview",    "오션뷰",     "view",         True),
    ("riverview",    "리버뷰",     "view",         True),
    ("mountainview", "산뷰",       "view",         False),
    ("lakeview",     "호수뷰",     "view",         False),    # addendum D3
    ("forestview",   "숲뷰",       "view",         False),    # addendum D3
    # ── Featured facilities ──────────────────────────────────
    ("trampoline",   "트램펄린",   "facility",     True),
    ("swimmingpool", "수영장",     "facility",     False),
    ("warmpool",     "온수풀",     "facility",     False),
    ("playground",   "놀이터",     "facility",     False),
    # ── Vibe / activity / season ─────────────────────────────
    ("private",      "프라이빗",   "vibe",         False),
    ("stargazing",   "별보기",     "activity",     False),
    ("autumn",       "단풍",       "season",       False),
    ("spring",       "벚꽃",       "season",       False),
    # ── Camp types ───────────────────────────────────────────
    ("autoCamping",  "오토캠핑",   "type",         False),
    ("glamping",     "글램핑",     "type",         False),
    ("caravan",      "카라반",     "type",         False),
    ("pension",      "펜션",       "type",         False),
    ("bungalow",     "방갈로",     "type",         False),
    # ── D1: site surface material ────────────────────────────
    ("surface_gravel",   "파쇄석",   "surface",  False),
    ("surface_deck",     "데크",     "surface",  False),
    ("surface_sand",     "마사토",   "surface",  False),
    ("surface_grass",    "잔디",     "surface",  False),
    ("surface_woodchip", "우드칩",   "surface",  False),
    ("surface_dirt",     "흙바닥",   "surface",  False),
    # ── D4: site space + parking layout ──────────────────────
    ("space_generous",   "넓은 사이트",   "space",   False),
    ("space_tight",      "좁은 사이트",   "space",   False),
    ("parking_on_site",  "사이트내 주차", "parking", False),
    ("parking_adjacent", "사이트옆 보조주차", "parking", False),
    ("parking_separate", "별도 주차장",   "parking", False),
    # ── D5: kids facility sub-axes ───────────────────────────
    ("sandpit",          "모래놀이장",   "kids_facility", False),
    ("animal_petting",   "동물체험",     "kids_facility", False),
    ("kids_pool",        "키즈수영장",   "kids_facility", False),
    ("kids_toilet",      "어린이화장실", "kids_facility", False),
    # ── D2: management (Mark axis — review-temperature driven) ─
    # Polarity flips negative for "noisy"/"신경 안 씀" via the existing
    # negation-aware review extractor. ComputeMarks reads these and
    # buckets camps into bib/recommended/notable/exceptional.
    ("mgmt_clean",       "깔끔",        "management", False),
    ("mgmt_clean2",      "청결",        "management", False),
    ("mgmt_pleasant",    "쾌적",        "management", False),
    ("mgmt_managed",     "관리",        "management", False),
    ("mgmt_neat",        "정돈",        "management", False),
    ("mgmt_neglected",   "방치",        "management", False),
    ("mgmt_old",         "노후",        "management", False),
]
