// Curated concept seed list — 1:1 port of `domain.concept_seeds.SEEDS`.
//
// Each entry: (id, korean_name, category, is_axis).
// Sources beyond this list (hashtag, facility) are auto-generated by
// BuildVocabulary using `source='hashtag'` or `source='facility'`.
//
// Categories used (free-form, but conventional):
//
//	audience, environment, facility, type, vibe, season, activity,
//	surface, view, space, parking, kids_facility, management
package domain

// ConceptSeed mirrors a row in the Python SEEDS list.
type ConceptSeed struct {
	ID       string
	Name     string
	Category string
	IsAxis   bool
}

// ConceptSeeds — order matches Python source so any downstream "first axis"
// semantics carry over.
var ConceptSeeds = []ConceptSeed{
	// Audience axes
	{"kids", "키즈캠핑", "audience", true},
	{"pets", "반려동반", "audience", true},
	// Environment / view
	{"valley", "계곡", "environment", true},
	{"oceanview", "오션뷰", "view", true},
	{"riverview", "리버뷰", "view", true},
	{"mountainview", "산뷰", "view", false},
	{"lakeview", "호수뷰", "view", false},   // addendum D3
	{"forestview", "숲뷰", "view", false},   // addendum D3
	// Featured facilities
	{"trampoline", "트램펄린", "facility", true},
	{"swimmingpool", "수영장", "facility", false},
	{"warmpool", "온수풀", "facility", false},
	{"playground", "놀이터", "facility", false},
	// Vibe / activity / season
	{"private", "프라이빗", "vibe", false},
	{"stargazing", "별보기", "activity", false},
	{"autumn", "단풍", "season", false},
	{"spring", "벚꽃", "season", false},
	// Camp types
	{"autoCamping", "오토캠핑", "type", false},
	{"glamping", "글램핑", "type", false},
	{"caravan", "카라반", "type", false},
	{"pension", "펜션", "type", false},
	{"bungalow", "방갈로", "type", false},
	// D1: site surface material
	{"surface_gravel", "파쇄석", "surface", false},
	{"surface_deck", "데크", "surface", false},
	{"surface_sand", "마사토", "surface", false},
	{"surface_grass", "잔디", "surface", false},
	{"surface_woodchip", "우드칩", "surface", false},
	{"surface_dirt", "흙바닥", "surface", false},
	// D4: site space + parking layout
	{"space_generous", "넓은 사이트", "space", false},
	{"space_tight", "좁은 사이트", "space", false},
	{"parking_on_site", "사이트내 주차", "parking", false},
	{"parking_adjacent", "사이트옆 보조주차", "parking", false},
	{"parking_separate", "별도 주차장", "parking", false},
	// D5: kids facility sub-axes
	{"sandpit", "모래놀이장", "kids_facility", false},
	{"animal_petting", "동물체험", "kids_facility", false},
	{"kids_pool", "키즈수영장", "kids_facility", false},
	{"kids_toilet", "어린이화장실", "kids_facility", false},
	// D2: management (Mark axis — review-temperature driven)
	// Polarity flips negative for "noisy"/"신경 안 씀" via the existing
	// negation-aware review extractor.
	{"mgmt_clean", "깔끔", "management", false},
	{"mgmt_clean2", "청결", "management", false},
	{"mgmt_pleasant", "쾌적", "management", false},
	{"mgmt_managed", "관리", "management", false},
	{"mgmt_neat", "정돈", "management", false},
	{"mgmt_neglected", "방치", "management", false},
	{"mgmt_old", "노후", "management", false},
}
